(major) Update to class-based Polymer2; new importing approach
Neovici/cosmoz-theme-switcher pull request #8
Opened 2019-05-21 08:53 UTC by cristinecula

Fixes #7

Changed to import .css files and use a single document-level style tag for holding the theme contents.

2019-05-21 12:24 UTC, cristinecula commented
This change is not BC so major should be bumped to 3.

2019-05-21 12:59 UTC, cristinecula commented
I will address the failing build tomorrow.

2019-05-22 08:08 UTC, cristinecula commented
Tests pass with 100% coverage.

2019-05-22 08:11 UTC, megheaiulian requested changes

2019-05-22 08:11 UTC, megheaiulian commented on cosmoz-theme-switcher.html
> +		const result = await fetch(href);
If `href` is null/undefined don't even fetch anything and just set the style to empty string.

2019-05-22 13:43 UTC, megheaiulian approved these changes

2019-05-23 14:07 UTC, dotpointer commented
@cristinecula How do I check out this branch? It is not in `remotes/origin`.

2019-05-24 06:34 UTC, cristinecula commented
@dotpointer The branch is in our fork of cosmoz-theme-switcher:
https://github.com/plumelo/cosmoz-theme-switcher/tree/feature/NEOV-326_new_importing_apprach
You can add `https://github.com/plumelo/cosmoz-theme-switcher.git` as another remote and checkout the branch from there.

2019-05-24 09:33 UTC, dotpointer requested changes
I read the code, tested the demo and also connected it to frontend using the https://github.com/Neovici/cosmoz-frontend/pull/1176 branch. It switched themes as expected in frontend, but the theme change did not persist on reloads - but that may be something to fix in frontend?

I also ran the tests, both on `master` and this branch. On `master` all tests passed. On this branch I got [12 errors](https://github.com/Neovici/cosmoz-theme-switcher/files/3216164/errors.txt).

**Can the test errors be fixed please?**

Except for this I approve.

2019-05-24 09:44 UTC, dotpointer requested changes
(Wrong PR, deleted.)

2019-05-24 10:19 UTC, cristinecula commented
> but the theme change did not persist on reloads - but that may be something to fix in frontend?
It is frontend's job to persist the user's setting, yes.

> Can the test errors be fixed please?
Did you do `yarn install` before `yarn test`?

2019-05-24 10:25 UTC, dotpointer commented
> > but the theme change did not persist on reloads - but that may be something to fix in frontend?
> > It is frontend's job to persist the user's setting, yes.
> 
> > Can the test errors be fixed please?
> > Did you do `yarn install` before `yarn test`?

`yarn install` is required to run `yarn test`, otherwise it complains about missing `polymer`. But I'll retry again and run `yarn install` again now.

2019-05-24 10:40 UTC, dotpointer commented
Now I have re-executed `yarn install` and then the tests.

That gave results, the [error file](https://github.com/Neovici/cosmoz-theme-switcher/files/3216440/errors2.txt) grew from ~526 lines to ~683 lines also including some errors about unexpected reserved words and illegal tokens. The number of 12 errors remains.

2019-05-24 14:55 UTC, nomego requested changes

2019-05-24 14:55 UTC, nomego commented on cosmoz-theme-switcher.html
> +		const result = await fetch(href);
The .catch() of Promises will throw errors, so should be surrounded by try/catch.
This will happen if offline for example.

2019-05-24 14:55 UTC, nomego commented on demo/helpers/x-foo.html
> +		class XFoo extends Polymer.Element {
This is a perfect example to:
```suggestion
		customElements.define('x-foo', class extends Polymer.Element {
		  static get template() { .. }
		});
```

2019-05-24 18:49 UTC, nomego commented
Should also fix most/all of #5

2019-05-27 13:05 UTC, cristinecula commented
@dotpointer fixed tests on saucelabs.

2019-05-28 09:29 UTC, nomego approved these changes

2019-05-28 09:29 UTC, merged